spring:
 application:
  name: eureka-service

server:
 port: 8302

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  service-url:
      defaultZone: http://localhost:8302/eureka
  server:
   waitTimeInMsWhenSyncEmpty: 0
   enableSelfPreservation: false

zuul:
 prefix: /api
 routes:
  db-service:
   path: /db-service/**
   url: http://localhost:8300
  user-service:
   path: /user-service/**
   url: http://localhost:8301
  turbine-dashboard:
   path: /turbine-dashboard/**
   url: http://localhost:8303